#!/usr/bin/env sh

if ! { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
    # Remove option --tab for new window
    alacritty -e "nvim \"$*\""
else
    # tmux session running
    tmux split-window -h "nvim \"$*\""
fi
