vim.pack.add({ 'https://github.com/romus204/tree-sitter-manager.nvim' })

require('tree-sitter-manager').setup({
  ensure_installed = {
    "javascript", "typescript", "tsx", "elixir", "eex", "heex",
    "erlang", "nu", "bash", "graphql",
    "c_sharp",
    "terraform", "hcl",
    "html", "css",
    "json", "json5",
    "yaml",
    "toml",
    "xml",
    "markdown", "markdown_inline",
    "mermaid",
    "fish",
    "awk",
    "make",
    "ninja",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "diff",
    "dockerfile",
    "nginx",
    "ssh_config",
    "sql",
    "scss",
    "vue",
    "svelte",
    "astro",
    "xml",
    "ocaml", "ocaml_interface",
    "haskell",
    "rust",
    "python",
    "regex",
    "jq",
    "lua",
    "luadoc",
    "vim",
    "vimdoc",
    "query",
    "comment",
    "printf",
    "http",
    "embedded_template",
  },
  auto_install = true,
})

vim.wo.foldmethod = 'expr'
vim.wo.foldexpr = 'v:lua.vim.treesitter.foldexpr()'
vim.wo.foldlevel = 99
