source = ~/.config/hypr/startup.conf

# monitor=,preferred,0x0,1
# Home setup
monitor=HDMI-A-3,preferred,0x0,1
monitor=DP-1,preferred,2560x0,1
monitor=eDP-1,preferred,5120x0,1
# monitor=eDP-1,disable

#Work  itminds
# monitor=eDP-1,1920x1080@165,0x0,1
# monitor=DVI-I-1,2560x1440@75,1920x0,1
# monitor=DVI-I-2,2560x1440@75,4480x0,1

monitor=Unknown-1,disable
monitor=Unknown-2,disable
# monitor=DVI-I-1,preffered,2560x0,1
# monitor=DVI-I-2,preffered,2560x0,1

input {
  kb_layout = us,dk
}

general {
  gaps_in = 5
  gaps_out = 5
  border_size = 1
  layout = dwindle
}

decoration {
  rounding = 4
}

source = ~/.config/hypr/keybinds.conf

windowrule = float on, match:class com.gabm.satty
windowrule = size 90% 90%, match:class com.gabm.satty
windowrule = center on, match:class com.gabm.satty
