exec-once = zellij --session main
exec-once = foot --server

exec-once = swww-daemon
exec-once = swww img ~/.config/awesome/themes/darkblue/wallpapers/itm-green.png

exec-once = waybar
exec-once = mako
exec-once = hypridle
